name: CI
on:
  pull_request:
    branches:
      - main
      - 'rc/**'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ 12, 14, 16 ]
        test_number: [1, 2]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.6

      - name: Lint, Test, and Build
        run: bash build-test.sh
