name: CI
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ 12, 14, 16 ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.6

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Lint, Test, and Build
        run: bash build.sh

      - name: Generate typedocs
        run: pnpm run docs:build

      - name: Deploy Docs To Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs
