name: Codacy Analysis CLI

on: ["pull_request"]

jobs:
  code-analysis-cli:
    name: Codacy Analysis CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Lint, Test, and Build
        run: bash build-test.sh

      - name: Run Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: lcov.info

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
